### ISSUE TITLE
Improve the "alt" content for images

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern-default-theme#1074]
### Is your feature request related to a problem?

Kind of (regarding best practices).

### What is the feature?

The current image rendering model does not check for the existence of associated alt text:

        <p itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
        <img loading="lazy" itemprop="url contentUrl" src="<txp:image_url link='0' />" alt="<txp:image_info type='alt' />">
        <meta itemprop="width" content="<txp:image_info type="w" />">
        <meta itemprop="height" content="<txp:image_info type="h" />">
        </p>

Perhaps this is room for a small amendment (use of a hyphen is acceptable in terms of SEO practices)?

        <p itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
            <img loading="lazy" itemprop="url contentUrl" src="<txp:image_url link='0' />" alt="alt="<txp:evaluate query test='<txp:image_info type="alt" />'><txp:image_info type="alt" /><txp:else />-</txp:evaluate>">
            <meta itemprop="width" content="<txp:image_info type="w" />">
            <meta itemprop="height" content="<txp:image_info type="h" />">
        </p>

As suggested by @bloatware here: https://forum.textpattern.com/viewtopic.php?pid=332047#p332047

**Comment by bloatware** [comment]
If you need it, `<txp:image_info type='alt' default='-' />` should do the trick.
