### ISSUE TITLE
Error with secondpass < 1

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern-default-theme#1095]
### Expected behaviour

No error messages.

### Actual behaviour

Tested with the default theme "Four Point Eight", if we change the `article` tag with `article_custom` as commented in the source code (Ref: https://github.com/textpattern/textpattern-default-theme/blob/main/dist/four-point-nine/pages/archive.txp#L105) we've got some errors message:

    Tag error: <txp:newer rel="prev">
                                    <txp:text item="newer" />
                                </txp:newer> ->  Textpattern Warning: secondpass < 1 while parsing form Aucun on page archive

    Tag error: <txp:older rel="next">
                                    <txp:text item="older" />
                                </txp:older> ->  Textpattern Warning: secondpass < 1 while parsing form Aucun on page archive
 

### Steps to reproduce

Need some Devs help for correction.

#### Additional information

Browser version and operating system: {Please write here}

**Comment by cara-tm** [comment]
... Solution (as explain here: https://forum.textpattern.com/viewtopic.php?pid=335295#p335295):

    <txp:article_custom class="article-list" form="article_listing" limit="10" wraptag="ul" />

                        

    <txp:hide process="1">
        <txp:article limit="10" pgonly="1" />
    </txp:hide>

                        

Note: `section="articles"` seems not needed.

**Comment by philwareham** [comment]
I've removed the comment, as I can't see a good way of explaining the code above with adding potentially confusing code.
