### ISSUE TITLE
Footer links on 404 error page

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-default-theme#142]
Using 4.7.0-dev, 404 pages have blank/empty `<li>` entries.

For example, non-existent section list: http://dev-demo.eu.textpattern.co/index.php?s=bogus-section-that-does-not-exist

![safariscreensnapz002](https://user-images.githubusercontent.com/226578/35243725-d91f92bc-ffb5-11e7-97a6-f6b9986d7cee.png)

Screencast attached in the zip file. I'll see if I can figure out what needs fixing.

[SafariScreenSnapz001.mp4.zip](https://github.com/textpattern/textpattern-default-theme/files/1653554/SafariScreenSnapz001.mp4.zip)

**Comment by petecooper** [comment]
Enabling debug mode shows 5x tag errors:

```
Tag error: <txp:search_input /> ->  Textpattern Notice: Form not found. search_input while parsing form None on page None
textpattern/lib/txplib_misc.php:4293 trigger_error()
textpattern/publish/taghandlers.php:1490 fetch_form()
search_input()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:596 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:520 processTags()
textpattern/lib/txplib_misc.php:5292 parse()
textpattern/publish.php:558 txp_die()
index.php:116 textpattern()
Tag error: <txp:linklist wraptag="ul" break="li" /> ->  Textpattern Notice: Form not found. plainlinks while parsing form None on page None
textpattern/lib/txplib_misc.php:4293 trigger_error()
textpattern/lib/txplib_misc.php:4327 fetch_form()
textpattern/publish/taghandlers.php:689 parse_form()
linklist()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:596 Textpattern\Tag\Registry->process()
textpattern/publish/taghandlers.php:5028 processTags()
txp_eval()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:596 Textpattern\Tag\Registry->process()
Tag error: <txp:linklist wraptag="ul" break="li" /> ->  Textpattern Notice: Form not found. plainlinks while parsing form None on page None
textpattern/lib/txplib_misc.php:4293 trigger_error()
textpattern/lib/txplib_misc.php:4327 fetch_form()
textpattern/publish/taghandlers.php:689 parse_form()
linklist()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:596 Textpattern\Tag\Registry->process()
textpattern/publish/taghandlers.php:5028 processTags()
txp_eval()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:596 Textpattern\Tag\Registry->process()
Tag error: <txp:linklist wraptag="ul" break="li" /> ->  Textpattern Notice: Form not found. plainlinks while parsing form None on page None
textpattern/lib/txplib_misc.php:4293 trigger_error()
textpattern/lib/txplib_misc.php:4327 fetch_form()
textpattern/publish/taghandlers.php:689 parse_form()
linklist()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:596 Textpattern\Tag\Registry->process()
textpattern/publish/taghandlers.php:5028 processTags()
txp_eval()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:596 Textpattern\Tag\Registry->process()
Tag error: <txp:linklist wraptag="ul" break="li" /> ->  Textpattern Notice: Form not found. plainlinks while parsing form None on page None
textpattern/lib/txplib_misc.php:4293 trigger_error()
textpattern/lib/txplib_misc.php:4327 fetch_form()
textpattern/publish/taghandlers.php:689 parse_form()
linklist()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:596 Textpattern\Tag\Registry->process()
textpattern/publish/taghandlers.php:5028 processTags()
txp_eval()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:596 Textpattern\Tag\Registry->process()
```

Investigating.

**Comment by petecooper** [comment]
OK, interesting find. Copying `error_default` to `error_404` (so the 404 error uses that instead) makes the links appear correctly and the tag errors disappear:

![safariscreensnapz003](https://user-images.githubusercontent.com/226578/35244210-54f6195a-ffb7-11e7-830c-c34f6848dc8c.png)
![safariscreensnapz004](https://user-images.githubusercontent.com/226578/35244211-550b17a6-ffb7-11e7-8afc-d05cc0383530.png)

**Comment by petecooper** [comment]
OK, this might be a snag in https://github.com/textpattern/textpattern rather than here. On the face of it, it looks like misc forms aren't parsed on `error_default` page. I will continue investigating.

**Comment by Bloke** [comment]
Possibly related: https://github.com/textpattern/textpattern/issues/1084

**Comment by petecooper** [comment]
Ah yes, that's it!

**Comment by Bloke** [comment]
> and yet, it works correctly if the form is error_404, so perhaps the issue lies with error_default.

Intriguing. Not what I'd expect at all.

ISTR our error handler tag has changed slightly so maybe there's a corner case here in `<txp:txp_die />` or something odd going on that means `error_default` doesn't "know" what the error number is, so it doesn't get caught properly.

**Comment by petecooper** [comment]
Any value in a couple of tag traces, @Bloke? I can run you off an `error_default` and `error_404` with a diff if that's helpful.

**Comment by Bloke** [comment]
Yes please.

**Comment by petecooper** [comment]
…and if the 404 error doesn't throw a tag trace in debug mode?

See: http://dev-demo.eu.textpattern.co/index.php?id=234 as an example

**Comment by Bloke** [comment]
Whaaaaaat?! Have we ever shown a tag trace under error conditions? Honestly can't remember. Would be pretty remiss of us if we didn't, but I can't recall.

**Comment by petecooper** [comment]
Not in 4.6.2, anyway: http://release-demo.eu.textpattern.co/index.php?id=123 <- no tag trace on 404 in debug mode.

Today I learned!

**Comment by Bloke** [comment]
Thanks for checking it out. I wonder if this is a feature of the changes to the `trace()` functionality in 4.6.2 and we just never noticed? And is it confined to 404s, or do you think any error pages are the same? Difficult to test I guess. Maybe 403 might be testable if we try and reach a directory that has `.htaccess` protection in it.

**Comment by petecooper** [comment]
Testing a 401 error (use `<txp:password_protect login="text" pass="text" />` in the default article with default forms and pages) also skips the tag trace in debug mode.

403 – I'm hazy on how we can achieve that in a directory. If the directory exists, then Textpattern won't be able to hop in and serve its files, surely…it's early, am I missing something?

**Comment by Bloke** [comment]
> a 401 error... also skips the tag trace in debug mode.

Drat. I'm not sure if this is by design or something we missed when altering the trace functions in 4.6.2. Will have to investigate further. Not necessarily a deal-breaker for the beta, but would be nice to fix if anyone has a clue.

> 403 – I'm hazy on how we can achieve that in a directory.

No, you're right. I was being a prawn. Move along...

**Comment by petecooper** [comment]
@Bloke - should I close this in favour of keeping https://github.com/textpattern/textpattern/issues/1124 as the main event? It's not technically a theme issue as it currently stands.

**Comment by Bloke** [comment]
Sure.
