### ISSUE TITLE
Search box buttons size on mobile viewport

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-default-theme#200]
Note the difference between the button size and connecting edge to the search box when viewing on mobile and desktop.

Desktop:

![safariscreensnapz001](https://user-images.githubusercontent.com/226578/38690496-284dc72e-3e76-11e8-885f-c86c42ad8ed4.png)

Mobile

![safariscreensnapz002](https://user-images.githubusercontent.com/226578/38690504-2e986dfa-3e76-11e8-9f6e-dbc2a86924c1.png)

Since the search box increases in size, along with a number of other elements, should the associated buttons grow/expand, too?

**Comment by philwareham** [comment]
Moved to proper repo. Closing here. Thanks.

**Comment by petecooper** [comment]
Ah, sorry @philwareham - I was short on sleep and misfiled! Thanks for moving.
