### ISSUE TITLE
“Everything is going to be alright”

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern-default-theme#217]
Maybe __Four Point Seven__ could add the new tribute category “*Everything is going to be alright*” attached to its first default article?
* * *

**Comment by bloatware** [comment]
Or make it the default site slogan?

**Comment by cara-tm** [comment]
;)

**Comment by philwareham** [comment]
Thinking further about this, I'm fine with it as it currently stands. The site slogan 'My pithy slogan' matches 'My site' at installation so I'm slightly adverse to changing it. We should drop 'Reciprocal affection' so we still have only 3 categories.
