### ISSUE TITLE
Hide nav bar `li`s where no articles exist

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-default-theme#226]
### Is your feature request related to a problem?

Nope.

### What is the feature?

When a new section is created, it automatically appears in the `nav` across all pages. There aren't necessarily articles in the section, and that creates a UX dead-end.

Rather than have another preference for "Include section in nav menu", is it viable to check whether a section has 1 or more articles and only show the link if it does? I realise this might need some form magic (variable, article_custom, limit 1, article ID, if/else and so on).

**Comment by Bloke** [comment]
Should be simple enough to use `<txp:evaluate>` to check if a section contains no articles. Or swap the logic around so each menu item is generated like this:

``` html
<txp:article_custom limit="1" section='<txp:section/>'>
   <li><txp:section title /></li>
</txp:article_custom>
```
Maybe. Not tested.

**Comment by bloatware** [comment]
I'd leave it with site designers, creating an empty section is a rather uncommon thing. Especially since checking for emptiness yields one extra db query per section.

**Comment by Bloke** [comment]
Yeah, the efficiency does go down if we have to check each time. I'm not fussed either way. Whatever seems most logical for 80% of users suits me. I'm all about the pareto.
