### ISSUE TITLE
Integrate `yield` with `permlink` where article URL is invalid

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-default-theme#248]
NTS: monitor progress/outcome of https://github.com/textpattern/textpattern/issues/1300 and https://github.com/textpattern/textpattern/issues/1301, propose a `yield` check on article title permlinks in article forms (see https://github.com/textpattern/textpattern-default-theme/tree/master/src/templates/forms/article - currently 3 forms).

**Comment by philwareham** [comment]
Hi Pete,

Can you supply example code for this? Cheers!

**Comment by petecooper** [comment]
Hi @philwareham - this might end up being a non-issue, especially if https://github.com/textpattern/textpattern/issues/1300 ends up with changes to the permlink generation (see https://github.com/textpattern/textpattern/issues/1300#issuecomment-397595532).

My high-level plan was to use `yield` to check if a valid permlink exists and then build the `a href` around it. Right now, if a URL has a 100% emoji title, no URL-title is generated, and the `permlink` is incorrect in some URL modes (see https://github.com/textpattern/textpattern/issues/1301#issue-332718762 for examples).

https://github.com/textpattern/textpattern/issues/1301 was resolved, and a messy (safe) URL is provided where no pretty one is offered up. I'll close for now.
