### ISSUE TITLE
`.token.entity` `background` in article preview

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-default-theme#282]
(Warning: this is nitpicking dialled to 11.)

Article HTML previews show encoded HTML entities with a different background to text and HTML tags. There appears to be a `background: hsla(0,0%,100%,.5);` rule applied.

I've attached a zoomed-in screengrab, note the lighter background on the `&#8217;` entity.

![screen shot 2018-08-10 at 16 19 42](https://user-images.githubusercontent.com/226578/43966363-9ac0299a-9cb9-11e8-908f-449f08503c30.png)

**Comment by philwareham** [comment]
This is intended. It's because this is a `<pre>` box and that's the background style I've given that element.
