### ISSUE TITLE
Missing absent favicon

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern-default-theme#292]
Currently (TXP-4.7.1-dev), Google Chrome browser display within it's console an error by looking for a missing favicon: `Failed to load resource: the server responded with a status of 404 (Not Found): /favicon.ico:1`

If you don't want to add such a kind of ressource with your default theme, may be it is the place for an image data: https://davidwalsh.name/blank-favicon

**Comment by philwareham** [comment]
Favicon is the concern of the user really and placed in the root of their website, I don't want to add either a favicon or that HTML example to the default theme. The hardcoded HTML would deny a real favicon from appearing if there was one in root. Thanks anyway. Closing.

**Comment by cara-tm** [comment]
Here is a real online website I found that uses the default theme without a custom favicon.

Maybe you could add such a "fake" favicon in order to prevent any console errors, preceded by a comment in the page template (currently there are lot of ones):

`<!-- Change below by your custom favicon image link instead -->`

![favicon-missing](https://user-images.githubusercontent.com/61045/46690563-e04ddc00-cc02-11e8-9a34-4a8f55d5bcbe.png)
