### ISSUE TITLE
Demo files - this repo or another one?

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-default-theme#298]
Now that there are properly hosted image/video files on the `default-theme` demo, it makes sense to house them.

@philwareham  - shall I add to this repo or another one?

**Comment by philwareham** [comment]
Sorry was out of office yesterday. Yes, we can add to this repo.

**Comment by petecooper** [comment]
Addressed by https://github.com/textpattern/textpattern-default-theme/commit/0acc69aa63cde5d951a65fbec7774b086bdd8f51
