### ISSUE TITLE
Remove reliance on Google Fonts

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-default-theme#381]
Currently we serve PT Serif form Google Fonts. Remove this and serve font locally due to third-party nature, online requirement, and privacy concerns associated with Google Font API.

**Comment by petecooper** [comment]
Nice one, @philwareham - I worked around the Google Fonts stuff [here](url
https://github.com/petecooper/textpattern-default-theme-no-remote) if it's of any use -- there's a slightly larger theme package because the font files and CSS are included, but it seems to work fine in real world testing.

**Comment by philwareham** [comment]
Nice. Unfortunately I can include the fonts in default theme as we recommend deleting setup folder after install. I did test base64 inine fonts in CSS but that made the CSS file large and unwieldy. So this is my only option really.

When I finally do our themes site I might offer and extended default theme that includes fonts and some JavaScript for additional functionality.
