### ISSUE TITLE
Develop install and compile strategy

### ISSUE THREAD

**Issue by gocom** [textpattern/textpattern-default-theme#43]
* Modules need to be able to be compiled to main JavaScript + CSS. Sass is already taken care of.
* Download dependencies using Bower and Composer.
* Make possible to create a Textpattern installation from the theme, or to install the theme a Textpattern installation.
* Add task/step for compiling SQL insert statement array for Textpattern's setup tool. We want the process be as simple as possible. Altho, we could also update the setup tool to read templates from filesystem, of course.

**Comment by philwareham** [comment]
This is done. The package can be installed via NPM or pulled from GitHub. Closing.
