### ISSUE TITLE
Need to create a standalone demo of the theme

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-default-theme#44]
I currently have a demo of this theme running on http://www.philwareham.co.uk along with its various extra options.

We really need to create a demo of it on the Textpattern official server, on a domain or subdomain relevant to the project, not my name. I'll contact Robert and see how he wants to handle that.

**Comment by philwareham** [comment]
@petecooper is handling this, I think.

**Comment by petecooper** [comment]
Sure, I'll add it to the demo site shopping list.

Please assign to me.

**Comment by petecooper** [comment]
Before I forget, the link to the theme demo (philwareham.co.uk) no longer works. Seemed a bit snarky to raise an issue for it, given the circumstances, so I didn't.

Also, I've been thinking about how we can best implement a theme demo. I'll gladly take the hosting burden and throw it up on textpattern.co, but for best effect I think a kitchen sink page is needed to showcase what the theme/framework can do.

I haven't been able to find one in the repo, but I do remember seeing stuff on philwareham.co.uk to this effect:

http://web.archive.org/web/20160310102400/http://philwareham.co.uk/

Is there a design patterns repo/reference, or should it become part of this one?

**Comment by philwareham** [comment]
I have hosting waiting for the demo, just haven't got round to actually installing a Textpattern instance. I'll try to remember to go it shortly. Cheers for the reminder!
