### ISSUE TITLE
Protocol-less external scripts

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-default-theme#56]
Currently, external components like Google Fonts, HTML5Shiv are loaded with http. If Textpattern runs on https, this will cause an error due to protocols not matching (i.e., http loads on https site). A solution would be to switch to protocol-relative URLs. Both Google Fonts and CDNJS are https-aware, so there's no immediate problem on that front.

However. IE7 and IE8 will download the Google Fonts CSS twice (see http://www.stevesouders.com/blog/2010/02/10/5a-missing-schema-double-download/ for info).

SSL is becoming more widespread. IE7 and IE8 is becoming _less_ widespread, so I move that the external resources be flipped to load in a protocol-relative fashion.

I'll take dibs if this is agreed.

**Comment by philwareham** [comment]
Ok, do it!!

**Comment by petecooper** [comment]
Closing; taken care of by https://github.com/textpattern/textpattern-default-theme/commit/914cf8d9e7e76a44854b634e0350d0b67269cf6e
