### ISSUE TITLE
Consider a `4.9.x` branch

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-default-theme#578]
Since 4.9 work is underway, we should probably have a `4.9.x` branch here for completeness, and fold it into `dev` at https://github.com/textpattern/textpattern

Edit: unless I've missed the point and `master` is basically 4.9…

**Comment by philwareham** [comment]
Yep, it's coming soon! Leave this issue open though. Thanks Pete.

**Comment by philwareham** [comment]
Oh, basically `dev` is (or will be) 4.9 though. We only branch off the previous versions.

**Comment by philwareham** [comment]
`master` branch now generates 4.9.x theme. Closing this issue.
