### ISSUE TITLE
4.6.0.alpha3

### ISSUE THREAD

**Issue by hcgtv** [textpattern/textpattern-default-theme#63]
A few things:

a) There is no default.css nor ie8.css in the release for copy/pasting purposes.

b) The forms, as per our Themes discussions on the forum, should be type.form_name.txp
ie. default.article.txp -> article.default.txp

c) Would be nice to have your textiled demo article included in the download for testing purposes.
http://www.philwareham.co.uk/articles/text-and-html-styling-examples

d) hcg_themes is ready to go for easy importing of this theme.
http://txptag.com/plugins/hcg_themes

e) Would it be ok at this stage to create a downloadable theme to spread around?

f) What would it take to create a one column theme from this?

*I enjoy your theme very much.*

**Comment by philwareham** [comment]
a) Sorry I totally forgot to add the binary. The zip file is attached to the release now.

b) If the theme filename format has changed then that will have to be raised as a separate issue for the next alpha. I have to admit I have been so busy at work that I haven't had a chance to play with Stef's theme branch as yet (even though I really want to).

c) Sure, I've now included it in the binary above.

d) Probably the same as b above - if that follows the same expected filename convention then I can amend at next alpha (which could be in next day or so).

e) Yep, it's the binary zip file. It can be shared as long as people understand it's alpha code.

f) It would take about three hours of my time, which is limited this week by my day job. I will do it soon as I can though!

:)
