### ISSUE TITLE
Errore tag:  <txp:meta_description />

### ISSUE THREAD

**Issue by stefano-buscaglia** [textpattern/textpattern-default-theme#64]
Hi,
i download a 4.6 public theme - alpha3 copy and paste all the data in form, page and style, plus the design-patterns-page.textile and i get the error reported:

Error tag: <txp: meta_description /> -> Textpattern Warning: tag nonexistent during the parsing module "None" in the "TestPage"

I got this in every standard page (home, archive, about)

have a nice day

Stefano

**Comment by philwareham** [comment]
The theme needs to be used with Textpattern 4.6 due to some extra tags that have been introduced. Are you using with 4.6 or an earlier Textpattern version?

**Comment by stefano-buscaglia** [comment]
Sorry philwareham my fault,
i installed the "latest version" of TextPattern but i do not realize that this is 4.5.7. 

Sorry

have a nice day

Stefano

**Comment by philwareham** [comment]
No worries. You can download the 4.6dev version from GitHub - it's fairly stable (I use it on a couple of production sites already).
