### ISSUE TITLE
Offer the 'Zero' theme for download

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-default-theme#677]
We should consider offering the Zero theme as a download. I know it's empty, but there is still value in having it as a downloadable asset. For someone installing Textpattern for the first time, they can use the whizzy default theme or the blank page one (aka Zero). They may decide to stick with the default, or hack around with it, or build from scratch with Zero, or acquire another theme, or whatever else.

Obviously this doesn't relate strictly to the default theme, but it's _a_ theme we supply in the distribution. It's a very useful thing to apply for throw-up style sites where getting the CMS installed without worrying about all the default content is part of the deploy.

Likewise if someone installs the default theme and wants to apply an official empty theme without any worry of the actual content (again, useful for someone who's getting to grips with things before delving deeper), then an "official" empty theme inside a .zip is a fast, low-friction way to pull the shutters on the site while build work takes place.

**Comment by philwareham** [comment]
OK, it'll probably need it's won repo though. I can't do anything until after New Year now as I have client deadlines up until Christmas Eve, then I am off work for a week.

**Comment by petecooper** [comment]
https://github.com/textpattern/textpattern-zero-theme

I'll take dibs.
