### ISSUE TITLE
Double comment forms

### ISSUE THREAD

**Issue by funtoosh** [textpattern/textpattern-default-theme#70]
Mhm, I keep getting double comment forms when using the latest issue of the theme w/ txp 4.5.7 -- anybody else get that?

Cheers,
Great great work so far!
-f

PS like this: http://www.spd-hiltrup.de/cms/aktuelles/led-glanz-mit-flecken

**Comment by philwareham** [comment]
Make sure the Textpattern preference “Automatically append comments to articles?” is set to “No”. Let me know. I don't think it's an issue directly with this theme.

**Comment by funtoosh** [comment]
Ah, sounds good, I'll give that a try later.

Cheers Phil,
-f


Am 14.12.2015 um 15:48 schrieb Phil Wareham <notifications@github.com>:

**Comment by funtoosh** [comment]
Yep, that fixed it, of course. Sorry, I haven't used the comment function in what seems like ages ...

And whilst I'm here, sth. I wanted to say for quite a while: thanx so much for all the work you put into the admin and default themes, imho these are the single most important updates to txp of the last couple years, and they make me coming back to use the cms. I even use bits & pieces of the default theme in my daily work, love it!

**Comment by philwareham** [comment]
Thanks, that's good to know!
