### ISSUE TITLE
CSS comments for the Hive Themes

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern-default-theme#77]
3 little CSS comments for the "Hive" & "Hive Neutral" Themes:

1.° Vertically align "select" field with others input fields (see how it renders into the "Forms" page):

    .txp-form-field {
            margin: 1em 0;
    /* new property */
    vertical-align: top;
    }

2.° Add white space arround content into select lists to show part of characters below the base line (i.e. "g" letters):

    select {
    /* new property */
    padding-top: 0.155em;
    
        padding-right:1.30769230769231em;
        background:url(...)
    }

3.° With your new very subtile effect around the fixed select list at the bottom of the pages, why do not change the black shadow below the header by a white one (this is just a visual choice)?

    .txp-header {
    box-shadow: 0 1em 1em #fff;
    }

**Comment by philwareham** [comment]
Sorry, wrong repo! See original thread for info.

**Comment by cara-tm** [comment]
@philwareham: in which repository can I attribute this?

**Comment by philwareham** [comment]
[Here please](https://github.com/philwareham/textpattern-hive-admin-theme/issues) :)
