### ISSUE TITLE
Text "Clear search" as icon

### ISSUE THREAD

**Issue by makss** [textpattern/textpattern-default-theme#78]
A small suggestion: replace the text "Clear search" on icon `ui-icon-close` or some other icon.

![](http://lady.yesnt.com/1/clear-search.png)

.

@philwareham please see this [issue](https://github.com/textpattern/textpattern/issues/866), perhaps it should have been set here.

**Comment by philwareham** [comment]
I'd rather leave the full descriptive text in place. The icon gives the impression you are removing text from search field but not necessarily clearing the search results filter. It also becomes confused with similar icon in safari search fields. Sorry but closing this request.
