### ISSUE TITLE
form: misc.images.txp - schema org markup is incomplete

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern-default-theme#80]
The Google  testing tool throws a hissy fit.
The spec being completely unusable, I went spying on the Guardian website…

Here is what I came up with to satisfy the testing tool:

```
  <figure itemprop="associatedMedia image" itemscope itemtype="http://schema.org/ImageObject">
    <meta itemprop="url" content="<txp:image_url link='0' />">
    <meta itemprop="width" content="<txp:image_info type="w" />">
    <meta itemprop="height" content="<txp:image_info type="h" />">
  <txp:image width="0" height="0" />
  <figcaption itemprop="caption">
    <txp:image_info type="caption" />
  </figcaption>
  </figure>
```

**Comment by philwareham** [comment]
Ok I'll look into it. The schema and testing tool change on a fairly regular basis (the current schema used to test fine).

**Comment by phiw13** [comment]
> … schema and testing tool change on a fairly regular basis…

Is that so? Sad, and typically Google. Iterating over various shades of lime.

Note that the default snippet tests out fine - when tested alone (via textarea input). But if you test a whole page (single article page, all default templates), then it fails.

Here is a sample article:
`https://dev.l-c-n.com/txp2/test-article-with-image`

**Comment by philwareham** [comment]
Bah! Doesn't help that Google's Structured Data Tool contradicts the examples given on Schema.org https://schema.org/ImageObject#exif

Working on fixes now.
