### ISSUE TITLE
Tag error into the latest default theme

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern-default-theme#889]
### Expected behaviour

A well formated TXP tag ;)

### Actual behaviour

I'm tested the latest (today's download) TXP 4.8.8 version and found a not well writing tag into the `body_header` form:

            <txp:section_list default_title='<txp:text item="home" />' include_default wraptag="ul" break="">
            <if_status>
            [...]
            <if_status>

### Steps to reproduce

Try the latest default theme.

#### Additional information

Browser version and operating system: not relevant here.

**Comment by philwareham** [comment]
Oops, my bad - will fix today. Thanks for the report.

**Comment by philwareham** [comment]
This should be fixed now!
