### ISSUE TITLE
`Images` h1 margin spacing

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-default-theme#91]
Using 4.7-dev (9779cfcc3d4d253b68e2dd2f2a9d0557), downloaded latest `dev` branch .zip today (June 8th 2017) if that helps, tested on Mac/Safari 10 and Mac/Chrome 59.

The *Images* h1 header on the Images tab inherits a CSS rule that sets `margin-bottom` to `0`, which brings the content below up when compared to similar tabs like Files and Links.

On the Files tab, the `h1.txp-heading` rendering of *Files* on desktop Safari comes out as 339x32, with a non-zero `margin-bottom`:

![files](https://user-images.githubusercontent.com/226578/26929691-7d8136d4-4c52-11e7-80a3-01e0f7cfb3a5.png)

On the Links tab, the `h1.txp-heading` rendering of *Links* on desktop Safari comes out as 339x32, with a non-zero `margin-bottom`:

![links](https://user-images.githubusercontent.com/226578/26929733-a382dd2e-4c52-11e7-9514-2820b1567156.png)

So far, so good. On the Images tab, the `h1.txp-heading` rendering of *Images* on desktop Safari as 339x32, with a zero `margin-bottom`:

![images-zero-margin-bottom](https://user-images.githubusercontent.com/226578/26929768-cd72818e-4c52-11e7-93ba-505b1a812280.png)

Note that this Images `h1` inherits different CSS rules to Files and Links (see red arrow). Commenting out that inherited rule brings the `margin-bottom` back in line with Files and Links (see red arrow on image below):

![images-fixed](https://user-images.githubusercontent.com/226578/26929840-0e8ac62c-4c53-11e7-8694-099cc949c7b2.png)

@philwareham - I'm happy to investigate why this is the case, and refresh my CSS chops. I know you have a lot of stuff on your list, so I'll wait to hear back before I do anything else.

**Comment by philwareham** [comment]
Steps to reproduce: Only happens when no search box is available (i.e. no images and files are uploaded yet).

I use this rule to reduce the vertical spacing on a few pages including the image editor (which unfortunately shares the same body `id` as the images list hence why this is happening.

Will fix. Thanks.
