### ISSUE TITLE
"Second pass < 1" error

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern-default-theme#936]
### Expected behaviour

No TXP warnings when `Number of extra parser sweeps` (Admin -> Preferences -> Advanced options) is set to `0`

### Actual behaviour

TXP preventing errors located into the `search_display` form.

### Steps to reproduce

Set Advanced Preferences `Number of extra parser sweeps` to `0` value.

#### Additional information

As explain by @bloatware on the forum (see: https://forum.textpattern.com/viewtopic.php?pid=332178), the `search_display` form need some amendments:

    <h1 itemprop="name"><txp:text item="search_results" /></h1>

    <txp:search_result_count />
    <txp:article[1] pgonly="1" pageby="10" />
    <txp:if_search_results>
    [...]

**Comment by cara-tm** [comment]
Update: No more needed based on the very latest commits (ask to Devs).

**Comment by etc** [comment]
That wasn't me.

**Comment by philwareham** [comment]
@cara-tm like this?...

https://github.com/textpattern/textpattern-default-theme/commit/636c2d7e96cc2fad020d56f93d6e3bf638361df4

@etc sorry, wrong person was referenced in original post. Please ignore!

**Comment by cara-tm** [comment]
@etc sorry. Corrected above.

**Comment by etc** [comment]
Not me buddy.

**Comment by etc** [comment]
Thanks!

**Comment by cara-tm** [comment]
@philwareham

Maybe it is a place for a comment to newbies:

    /* For "Number of extra parser sweeps" set to zero in "Advanced options" preferences (more info here: https://bit.ly/3iBde8m) */
    <txp:article[1] pgonly="1" />

**Comment by bloatware** [comment]
I think (to test) you don't need this `<txp:article[1] pgonly="1" />` tag at all if you replace

```
<txp:article class="article-list" wraptag="ul" />
```
with
```
<txp:article[1] class="article-list" wraptag="ul" />
```

**Comment by cara-tm** [comment]
@bloatware: Yep. That seems to work (based on my tests) ;)
