### ISSUE TITLE
Include sensible defaults for OpenGraph

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-default-theme#97]
Out of the box, Textpattern doesn't include OpenGraph elements in `head`. This means Facebook and the like use best-guess to populate article summaries, and it looks a bit wonky.

As of 4.6.2, the default looks like this:

![screen shot 2017-08-29 at 11 29 08](https://user-images.githubusercontent.com/226578/29816824-984c9788-8cad-11e7-926b-abed070c890b.png)

```
My site: Welcome to your site
Welcome to your site Posted Aug 29, 12:00 AM Comments 1 What do you want to do next? Modify or delete this article? The article list is the place to start. Change this site’s name, or modify the style of the URLs? It’s all up to your preferences. Get yourself acquainted with Textile, the humane mark...
```

Is OpenGraph in scope for some sensible defaults? Maybe paring back the description (and improving readability) by specifying the article excerpt or first paragraph of the body, removing the posted date, and removing the number of comments.

I really, really like the metadata included in the default theme…so much so that I use it for cribbing on new builds. Basic OpenGraph would be sufficient to make a Facebook share more likely, and it need not be overly complex.

**Comment by philwareham** [comment]
Kind of like this?: https://github.com/philwareham/hive-framework/blob/master/src/templates/forms/meta_open_graph.misc.txp

I have been apprehensive about including too much meta data into page templates, as where do we stop? Twitter cards too? JSON-LD?

Once the themes branch has stabilised I think we can definitely add this in though, as the addition of extra forms will be relatively straightforward.

**Comment by petecooper** [comment]
Thanks, @philwareham -- exactly like that, yes!

I agree with the point of going too far, too. My take is that it's work that's done once and will benefit many people using Textpattern, countless more who view the content via shares and while OpenGraph is used by Facebook, it's not a _solely_ Facebook thing (e.g Pinterest speaks it, as well as Schema.org).

It shouldn't be a be-all and end-all solution, those people that want to hack at it can do, of course. It's a handful of lines of code, some database calls, and if it's easily removable for folks that just don't want/need it, everyone wins.

**Comment by petecooper** [comment]
Bump to 4.8 milestone?

**Comment by philwareham** [comment]
Yep! :)

**Comment by philwareham** [comment]
Done.

**Comment by petecooper** [comment]
Nice one @philwareham – thank you very much!

**Comment by philwareham** [comment]
🍰
